//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsigCabecera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AsigCabecera()
        {
            this.AsigNovedadDetalles = new HashSet<AsigNovedadDetalle>();
        }
    
        public int RECID { get; set; }
        public string IDRegitro { get; set; }
        public Nullable<int> RECIDColaborador { get; set; }
        public string Colaborador { get; set; }
        public Nullable<double> Total { get; set; }
    
        public virtual Colaboradore Colaboradore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsigNovedadDetalle> AsigNovedadDetalles { get; set; }
    }
}
