//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatagridColaborador
    {
        public int RECID { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Cedula_o_Pasaporte { get; set; }
        public string Codigo_de_empleado { get; set; }
        public Nullable<System.DateTime> Fecha_de_ingreso { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Estatus_Laboral { get; set; }
        public string Banco { get; set; }
        public string Tipo_de_Cuenta { get; set; }
        public string Cuenta_Bancaria { get; set; }
        public string Puesto { get; set; }
        public string Email { get; set; }
        public string Sexo { get; set; }
        public Nullable<bool> Usuario_del_Sistema { get; set; }
    }
}
