//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataGridPuesto
    {
        public int RECID { get; set; }
        public string ID_Puesto { get; set; }
        public string Puesto { get; set; }
        public string Departamento { get; set; }
        public Nullable<int> Cantidad_Disponible { get; set; }
        public double Salario { get; set; }
        public string Frecuencia_del_salario { get; set; }
        public string Deberes { get; set; }
        public Nullable<double> Pago_por_horas { get; set; }
    }
}
