//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class NominaDetalle1
    {
        public int RECID { get; set; }
        public Nullable<int> RECIDCabecera { get; set; }
        public Nullable<int> RECIDAsingCabecera { get; set; }
        public string IDColaborador { get; set; }
        public string Nombre { get; set; }
        public Nullable<double> TotalDeducciones { get; set; }
        public Nullable<double> TotalIngreso { get; set; }
        public Nullable<double> TotalPagar { get; set; }
    
        public virtual NominaCabecera NominaCabecera { get; set; }
    }
}
