//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Novedade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Novedade()
        {
            this.AsigNovedadDetalles = new HashSet<AsigNovedadDetalle>();
        }
    
        public int RECID { get; set; }
        public string IDNOVEDAD { get; set; }
        public string Nombre { get; set; }
        public string TipoNovedad { get; set; }
        public Nullable<bool> AplicaTax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsigNovedadDetalle> AsigNovedadDetalles { get; set; }
    }
}
