//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class vNomina
    {
        public int RECID { get; set; }
        public string IDRegitro { get; set; }
        public string Codigo_de_empleado { get; set; }
        public string Colaborador { get; set; }
        public Nullable<double> Deducciones { get; set; }
        public Nullable<double> Ingreso { get; set; }
        public Nullable<double> Total { get; set; }
    }
}
